### ISSUE TITLE
We should rename ARTIFACT to ARTIFACT_GROUP or similar

### ISSUE THREAD

**Issue by destijl** [ForensicArtifacts/artifacts#139]
Here's something I've seen a couple of times now, it's not obvious that the REGISTRY_VALUE is the artifact. People think they need to create a separate ARTIFACT object to hold it. In reality you only need to do this if you are grouping artifacts into a meta artifact.

ARTIFACT_GROUP
ARTIFACT_LIST
META_ARTIFACT

would probably be more intuitive names.

```
name: ConfickerIndicators
doc: Conficker Indicators.
sources:
- type: ARTIFACT
  attributes:
    names:
      - ConfickerWindowsRegKeys
supported_os: [Windows]
urls: ['https://www.iocbucket.com/iocs/e2903921f8b21d71dc88f34bee8b2f3491ea4656']
---
name: ConfickerWindowsRegKeys
doc: Windows Conficker IOCs.
sources:
- type: REGISTRY_VALUE
  attributes:
    key_value_pairs:
    - {key: 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\[RANDOM CHARACTERS]\"ImagePath"', value: '"%System%\svchost.exe -k netsvcs"'}
    - {key: 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\[WORM GENERATED SERVICE NAME]\"ImagePath"', value: '%SystemRoot%\system32\svchost.exe -k netsvcs'}
    - {key: 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\explorer\Advanced\Folder\Hidden\SHOWALL\"CheckedValue"', value: '0'}
    - {key: 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\"TcpNumConnections"', value: '00FFFFFE'}
supported_os: [Windows]
urls: ['https://www.iocbucket.com/iocs/e2903921f8b21d71dc88f34bee8b2f3491ea4656']
```
