### ISSUE TITLE
Consider how CurrentControlSet is defined

### ISSUE THREAD

**Issue by joachimmetz** [ForensicArtifacts/artifacts#401]
Determine how to properly define CurrentControlSet for Windows NT and 9x/Me Registry Files.

* In Windows 9x/Me CurrentControlSet is a "real" key
* In Windows NT CurrentControlSet is a virtual key

https://github.com/libyal/winreg-kb/blob/master/docs/sources/system-keys/Current-control-set.md

Maybe define `%ControlSets%` or `%AllControlSets%` for all control sets?

**Comment by joachimmetz** [comment]
What if a Windows NT SYSTEM file contains a CurrentControlSet key?

**Comment by cugu** [comment]
`%%current_control_set%%` is already [defined](https://github.com/ForensicArtifacts/artifacts/blob/master/data/windows.yaml#L1708:L1715). This could be extended for pre-NT systems:
``` yaml
name: WindowsRegistryCurrentControlSets
sources:
- type: REGISTRY_VALUE
  attributes: {key_value_pairs: [{key: 'HKEY_LOCAL_MACHINE\System\Select', value: 'Current'}]}
- type: REGISTRY_KEY
  attributes: {keys: ['HKEY_LOCAL_MACHINE\System\CurrentControlSet']}
provides: [current_control_set]
```

If all ControlSets should be considered a `%%control_set%%` could be defined as:
``` yaml
name: WindowsRegistryControlSets
sources:
- type: REGISTRY_KEY
  attributes:
    keys: 
      - 'HKEY_LOCAL_MACHINE\System\ControlSet*'
      - 'HKEY_LOCAL_MACHINE\System\CurrentControlSet'
provides: [control_set]
```

To differentiate between different Windows versions conditions ( e.g. `conditions: [os_major_version >= 5]`) could be used.
