### ISSUE TITLE
Add NTFS USN change journal artifact

### ISSUE THREAD

**Issue by m1435** [ForensicArtifacts/artifacts#448]
From [Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/fileio/change-journals):

> [T]he NTFS file system maintains an update sequence number (USN) change journal. When any change is made to a file or directory in a volume, the USN change journal for that volume is updated with a description of the change and the name of the file or directory.

The USN change journal is a useful artifact to track the creation, modification, and deletion of files in the file system. It is, for example, supported by Plaso with the [`usnjrnl` parser](https://plaso.readthedocs.io/en/latest/sources/api/plaso.parsers.html#plaso.parsers.ntfs.NTFSUsnJrnlParser).

Other than for $MFT and $Logfile, there is no predefined artifact for the corresponding `\$Extend\$UsnJrnl` file that contains the change journal.

I suggest adding something along the following to https://github.com/ForensicArtifacts/artifacts/blob/main/data/ntfs.yaml:
```yaml
name: NTFSUsnJrnlFiles
doc: |
  The NTFS $UsnJrnl:$J and $UsnJrnl:$Max file system metadata files.
sources:
- type: FILE
  attributes:
    paths:
    - '%%environ_systemdrive%%\$Extend\$UsnJrnl'
    separator: '\'
labels: [System]
supported_os: [Windows]
```

I've tested this as a custom artifact definition in Plaso/log2timeline and the `usnjrnl` parser, and it appears to be working.

Potentially related issue: https://github.com/ForensicArtifacts/artifacts/issues/431
