### ISSUE TITLE
Spec Proposal: Authors field

### ISSUE THREAD

**Issue by cugu** [ForensicArtifacts/artifacts#494]
I think it would be nice to have an `authors` field for artifacts, to give credit to artifact definition creators, editors and maintainers. Git blame has this information to a certain extent, but reformatting, moving or editing the yaml files might hide that information over time. 

I would imagine it as an optional list of strings that every author can fill or extent to their liking, e.g. their GitHub username, a full name, an email, ...

Example:
```yaml
name: WindowsEventTracingLogFiles
doc: Event Tracing for Windows (ETW) log files.
authors: 
  - joachimmetz
  - Another Author <author@example.com>
  - Last Author
sources:
- type: FILE
  attributes:
    paths:
    - '%%environ_allusersappdata%%\Microsoft\Diagnosis\ETLLogs\ShutdownLogger\*.etl'
    separator: '\'
supported_os: [Windows]
```
